UNKNOWN_SYNC_STAGE_ID = 0
FAST_SYNC_STAGE_ID = 1
CONSENSUS_MATCH_SYNC_STAGE_ID = 2
ADDITIVE_SYNC_STAGE_ID = 3
FULLY_SYNCED_STAGE_ID = 4

CHRONOLOGICAL_BLOCK_HASH_FRAGMENT_TYPE_ID = 1
CHAIN_HEAD_BLOCK_HASH_FRAGMENT_TYPE_ID = 2